"""SCREAMING_SNAKE event-type identifiers — the value of ``code`` on
every error this client constructs.

Mirrors ``client-rust/main/src/error_codes.rs::codes`` — same constant
names, same string values.
"""

# Validation
VALUE_NOT_POSITIVE = "VALUE_NOT_POSITIVE"
VALUE_NOT_NON_NEGATIVE = "VALUE_NOT_NON_NEGATIVE"
VALUE_EMPTY = "VALUE_EMPTY"
COLLECTION_EMPTY = "COLLECTION_EMPTY"
ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
ENTITY_ALREADY_EXISTS = "ENTITY_ALREADY_EXISTS"
STATUS_MISMATCH = "STATUS_MISMATCH"
STATUS_FORBIDDEN = "STATUS_FORBIDDEN"

# Builder
COMMAND_TYPE_URL_MISSING = "COMMAND_TYPE_URL_MISSING"
COMMAND_PAYLOAD_MISSING = "COMMAND_PAYLOAD_MISSING"
COMMAND_SEQUENCE_MISSING = "COMMAND_SEQUENCE_MISSING"

# Conversion
ANY_TYPE_MISMATCH = "ANY_TYPE_MISMATCH"
ANY_DECODE_FAILED = "ANY_DECODE_FAILED"
PROTO_UUID_INVALID = "PROTO_UUID_INVALID"
TIMESTAMP_PARSE_FAILED = "TIMESTAMP_PARSE_FAILED"

# Transport / connection
ENDPOINT_PARSE_FAILED = "ENDPOINT_PARSE_FAILED"
ENDPOINT_INVALID_URI = "ENDPOINT_INVALID_URI"
CONNECTION_FAILED = "CONNECTION_FAILED"
CONNECTION_FAILED_MAX_RETRIES = "CONNECTION_FAILED_MAX_RETRIES"
TRANSPORT_ERROR = "TRANSPORT_ERROR"
GRPC_ERROR = "GRPC_ERROR"

# Dispatch — common
HANDLER_WRONG_RESPONSE_KIND = "HANDLER_WRONG_RESPONSE_KIND"
HANDLER_WRONG_REQUEST_KIND = "HANDLER_WRONG_REQUEST_KIND"
NO_HANDLER_REGISTERED = "NO_HANDLER_REGISTERED"
MISSING_COMMAND_BOOK = "MISSING_COMMAND_BOOK"
MISSING_COMMAND_PAGE = "MISSING_COMMAND_PAGE"
MISSING_COMMAND_PAYLOAD = "MISSING_COMMAND_PAYLOAD"
NOTIFICATION_DECODE_FAILED = "NOTIFICATION_DECODE_FAILED"
REJECTION_NOTIFICATION_DECODE_FAILED = "REJECTION_NOTIFICATION_DECODE_FAILED"

# Dispatch — saga
MISSING_SAGA_SOURCE = "MISSING_SAGA_SOURCE"
EMPTY_SAGA_SOURCE = "EMPTY_SAGA_SOURCE"
MISSING_SAGA_EVENT_PAYLOAD = "MISSING_SAGA_EVENT_PAYLOAD"
SAGA_INVALID_TYPE_URL = "SAGA_INVALID_TYPE_URL"
SAGA_HANDLER_UNSUPPORTED_RETURN_TYPE = "SAGA_HANDLER_UNSUPPORTED_RETURN_TYPE"

# Dispatch — process manager
MISSING_PM_TRIGGER = "MISSING_PM_TRIGGER"
EMPTY_PM_TRIGGER = "EMPTY_PM_TRIGGER"
MISSING_PM_EVENT_PAYLOAD = "MISSING_PM_EVENT_PAYLOAD"
PM_INVALID_TYPE_URL = "PM_INVALID_TYPE_URL"
PM_HANDLER_WRONG_RETURN_TYPE = "PM_HANDLER_WRONG_RETURN_TYPE"

# Dispatch — upcaster
UPCASTER_WRONG_RESPONSE_KIND = "UPCASTER_WRONG_RESPONSE_KIND"

# Build-time validation
HANDLER_FIELD_EMPTY_STRING = "HANDLER_FIELD_EMPTY_STRING"
HANDLER_FIELD_EMPTY_LIST = "HANDLER_FIELD_EMPTY_LIST"
HANDLER_STATE_NOT_TYPE = "HANDLER_STATE_NOT_TYPE"
HANDLER_UNKNOWN_KIND = "HANDLER_UNKNOWN_KIND"
ROUTER_NO_HANDLERS = "ROUTER_NO_HANDLERS"
