"""The angzarr router: the shared Rust engine (angzarr-router's router-ffi
cdylib) bound through cffi (ABI mode).

Dispatch, state rebuild, rejection and compensation routing all run in the
router; this package populates its dispatch tables and crosses the C ABI.
Code generated by ``angzarr codegen python`` (this repository's codegen/
templates) targets this surface:

    from angzarr_client.router import (
        Router, AggregateDispatch, Rebuilder, ProjectorDispatch,
        SagaDispatch, ProcessManagerDispatch, Destinations,
        CommandContext, FactRecord, PageContext, current_cover, current_page,
        CodedError, reject, GrpcCode, abi_version, AbiVersionError,
        WILDCARD_DOMAIN,
    )
"""

from ._abi import AbiVersionError
from ._dispatch import (
    WILDCARD_DOMAIN,
    AggregateDispatch,
    CodedError,
    CommandContext,
    Destinations,
    FactRecord,
    GrpcCode,
    PageContext,
    ProcessManagerDispatch,
    ProjectorDispatch,
    Rebuilder,
    Router,
    SagaDispatch,
    abi_version,
    any_decode_error,
    current_cover,
    current_page,
    pack,
    reject,
)

__all__ = [
    "WILDCARD_DOMAIN",
    "AbiVersionError",
    "AggregateDispatch",
    "CodedError",
    "CommandContext",
    "Destinations",
    "FactRecord",
    "GrpcCode",
    "PageContext",
    "ProcessManagerDispatch",
    "ProjectorDispatch",
    "Rebuilder",
    "Router",
    "SagaDispatch",
    "abi_version",
    "any_decode_error",
    "current_cover",
    "current_page",
    "pack",
    "reject",
]
