"""Angzarr Python client library for gRPC services."""

from importlib.metadata import version as _version

__version__ = _version("angzarr-client")

from .builder import CommandBuilder, QueryBuilder
from .client import (
    DEFAULT_MAX_EVENT_BOOKS,
    DEFAULT_RPC_TIMEOUT,
    CommandHandlerClient,
    DomainClient,
    QueryClient,
    SpeculativeClient,
    TransportMode,
    resolve_ch_endpoint,
)
from .compensation import (
    CompensationContext,
    DelegationOptions,
    PMRevocationResponse,
    delegate_to_framework,
    emit_compensation_events,
    is_notification,
    pm_delegate_to_framework,
    pm_emit_compensation_events,
)
from .destinations import Destinations
from .errors import (
    ClientError,
    CommandRejectedError,
    ConnectionError,
    GRPCError,
    InvalidArgumentError,
    InvalidTimestampError,
    TransportError,
)
from .helpers import (
    CORRELATION_ID_HEADER,
    DEFAULT_EDITION,
    META_ANGZARR_DOMAIN,
    PROJECTION_DOMAIN_PREFIX,
    PROJECTION_TYPE_URL,
    TYPE_URL_PREFIX,
    UNKNOWN_DOMAIN,
    WILDCARD_DOMAIN,
    correlated_metadata,
    destination_map,
    full_type_url,
    full_type_url_for,
    implicit_edition,
    now,
    parse_timestamp,
    proto_to_uuid,
    proto_uuid_to_hex,
    type_name_from_url,
    type_url,
    type_url_matches,
    type_url_matches_exact,
    uuid_to_proto,
)
from .identity import (
    INVENTORY_PRODUCT_NAMESPACE,
    cart_root,
    compute_root,
    customer_root,
    fulfillment_root,
    inventory_product_root,
    inventory_root,
    order_root,
    product_root,
    to_proto_bytes,
)
from .retry import (
    ExponentialBackoffRetry,
    RetryPolicy,
    default_retry_policy,
)
from .router import (
    BuildError,
    CommandHandlerRouter,
    DispatchError,
    ProcessManagerResponse,
    ProcessManagerRouter,
    ProjectorRouter,
    RejectionHandlerResponse,
    Router,
    SagaHandlerResponse,
    SagaRouter,
    UpcasterRouter,
    applies,
    command_handler,
    handles,
    handles_fact,
    process_manager,
    projector,
    rejected,
    saga,
    state_factory,
    upcaster,
    upcasts,
)
from .router.server import (
    CommandHandlerGrpc,
    ProcessManagerGrpc,
    ProjectorGrpc,
    SagaGrpc,
    UpcasterGrpc,
)
from .server import (
    DEFAULT_BIND_HOST,
    ENV_BIND_ADDRESS,
    ServerConfig,
    cleanup_socket,
    configure_logging,
    create_server,
    get_transport_config,
    resolve_bind_address,
    run_command_handler_server,
    run_process_manager_server,
    run_projector_server,
    run_saga_server,
    run_server,
    run_upcaster_server,
)
from .testing import (
    DEFAULT_TEST_NAMESPACE,
    ScenarioContext,
    make_command_book,
    make_command_page,
    make_cover,
    make_event_book,
    make_event_page,
    make_timestamp,
    uuid_for,
    uuid_obj_for,
    uuid_str_for,
)
from .testing import pack_event as testing_pack_event
from .validation import (
    require_exists,
    require_non_negative,
    require_not_empty,
    require_not_empty_str,
    require_not_exists,
    require_positive,
    require_status,
    require_status_not,
)
from .wrappers import (
    CommandBook,
    CommandPage,
    CommandResponse,
    Cover,
    CoverBearer,
    EventBook,
    EventPage,
    Query,
    Wrapped,
)

__all__ = [
    # Clients
    "CommandHandlerClient",
    "QueryClient",
    "SpeculativeClient",
    "DomainClient",
    "TransportMode",
    "resolve_ch_endpoint",
    "DEFAULT_RPC_TIMEOUT",
    "DEFAULT_MAX_EVENT_BOOKS",
    # Router (unified)
    "Router",
    "BuildError",
    "DispatchError",
    "CommandHandlerRouter",
    "SagaRouter",
    "ProcessManagerRouter",
    "ProjectorRouter",
    "UpcasterRouter",
    "SagaHandlerResponse",
    "ProcessManagerResponse",
    "RejectionHandlerResponse",
    "command_handler",
    "saga",
    "process_manager",
    "projector",
    "upcaster",
    "handles",
    "handles_fact",
    "applies",
    "rejected",
    "state_factory",
    "upcasts",
    # gRPC server adapters
    "CommandHandlerGrpc",
    "SagaGrpc",
    "ProcessManagerGrpc",
    "ProjectorGrpc",
    "UpcasterGrpc",
    # Errors
    "ClientError",
    "ConnectionError",
    "TransportError",
    "GRPCError",
    "InvalidArgumentError",
    "InvalidTimestampError",
    "CommandRejectedError",
    # Constants
    "UNKNOWN_DOMAIN",
    "WILDCARD_DOMAIN",
    "DEFAULT_EDITION",
    "META_ANGZARR_DOMAIN",
    "PROJECTION_DOMAIN_PREFIX",
    "PROJECTION_TYPE_URL",
    "TYPE_URL_PREFIX",
    "CORRELATION_ID_HEADER",
    # Pure utilities (non-accessor — accessors live on wrapper classes)
    "correlated_metadata",
    "destination_map",
    "implicit_edition",
    "uuid_to_proto",
    "proto_to_uuid",
    "proto_uuid_to_hex",
    "type_url",
    "type_name_from_url",
    "type_url_matches",
    "type_url_matches_exact",
    "full_type_url",
    "full_type_url_for",
    "now",
    "parse_timestamp",
    # Builders
    "CommandBuilder",
    "QueryBuilder",
    # Wrappers (user-facing object surface for framework protos)
    "Wrapped",
    "CoverBearer",
    "Cover",
    "EventBook",
    "CommandBook",
    "Query",
    "EventPage",
    "CommandPage",
    "CommandResponse",
    # Server
    "configure_logging",
    "get_transport_config",
    "resolve_bind_address",
    "ENV_BIND_ADDRESS",
    "DEFAULT_BIND_HOST",
    "create_server",
    "run_server",
    "run_command_handler_server",
    "run_saga_server",
    "run_process_manager_server",
    "run_projector_server",
    "run_upcaster_server",
    "ServerConfig",
    "cleanup_socket",
    # Testing helpers (mirror angzarr_client::testing in Rust)
    "DEFAULT_TEST_NAMESPACE",
    "ScenarioContext",
    "make_cover",
    "make_event_page",
    "make_event_book",
    "make_command_page",
    "make_command_book",
    "make_timestamp",
    "testing_pack_event",
    "uuid_for",
    "uuid_str_for",
    "uuid_obj_for",
    # Validation
    "require_exists",
    "require_not_exists",
    "require_positive",
    "require_non_negative",
    "require_not_empty",
    "require_not_empty_str",
    "require_status",
    "require_status_not",
    # Identity
    "INVENTORY_PRODUCT_NAMESPACE",
    "compute_root",
    "inventory_product_root",
    "customer_root",
    "product_root",
    "order_root",
    "inventory_root",
    "cart_root",
    "fulfillment_root",
    "to_proto_bytes",
    # Compensation
    "CompensationContext",
    "DelegationOptions",
    "PMRevocationResponse",
    "delegate_to_framework",
    "emit_compensation_events",
    "is_notification",
    "pm_delegate_to_framework",
    "pm_emit_compensation_events",
    # Destinations
    "Destinations",
    # Retry
    "RetryPolicy",
    "ExponentialBackoffRetry",
    "default_retry_policy",
]
