"""Angzarr Python client library for gRPC services."""

from importlib.metadata import version as _version

__version__ = _version("angzarr-client")

from .builder import CommandBuilder, QueryBuilder
from .client import (
    CommandHandlerClient,
    DomainClient,
    QueryClient,
    SpeculativeClient,
)
from .compensation import (
    CompensationContext,
    RejectionHandlerResponse,
    delegate_to_framework,
    emit_compensation_events,
    pm_delegate_to_framework,
    pm_emit_compensation_events,
)
from .destinations import Destinations
from .errors import (
    ClientError,
    CommandRejectedError,
    ConnectionError,
    GRPCError,
    InvalidArgumentError,
    InvalidTimestampError,
    TransportError,
)
from .event_packing import new_event_book, new_event_book_multi, pack_event, pack_events
from .helpers import (
    DEFAULT_EDITION,
    META_ANGZARR_DOMAIN,
    PROJECTION_DOMAIN_PREFIX,
    PROJECTION_TYPE_URL,
    TYPE_URL_PREFIX,
    UNKNOWN_DOMAIN,
    WILDCARD_DOMAIN,
    correlation_id,
    destination_map,
    domain,
    edition,
    edition_is_empty,
    edition_name_or_default,
    full_type_url,
    full_type_url_for,
    has_correlation_id,
    next_sequence,
    now,
    parse_timestamp,
    proto_to_uuid,
    proto_uuid_to_hex,
    root_id_hex,
    root_uuid,
    type_name_from_url,
    type_url,
    type_url_matches,
    type_url_matches_exact,
    uuid_to_proto,
)
from .identity import (
    INVENTORY_PRODUCT_NAMESPACE,
    cart_root,
    compute_root,
    customer_root,
    fulfillment_root,
    inventory_product_root,
    inventory_root,
    order_root,
    product_root,
    to_proto_bytes,
)
from .router import (
    BuildError,
    CommandHandlerRouter,
    DispatchError,
    ProcessManagerResponse,
    ProcessManagerRouter,
    ProjectorRouter,
    Router,
    SagaHandlerResponse,
    SagaRouter,
    UpcasterRouter,
    applies,
    command_handler,
    handles,
    process_manager,
    projector,
    rejected,
    saga,
    state_factory,
    upcaster,
    upcasts,
)
from .router.server import (
    CommandHandlerGrpc,
    ProcessManagerGrpc,
    ProjectorGrpc,
    SagaGrpc,
    UpcasterGrpc,
)
from .saga_context import SagaContext
from .server import (
    cleanup_socket,
    configure_logging,
    create_server,
    get_transport_config,
    run_server,
)
from .validation import (
    require_exists,
    require_non_negative,
    require_not_empty,
    require_not_empty_str,
    require_not_exists,
    require_positive,
    require_status,
    require_status_not,
)
from .wrappers import (
    CommandBookW,
    CommandPageW,
    CommandResponseW,
    CoverW,
    EventBookW,
    EventPageW,
    QueryW,
)

__all__ = [
    # Clients
    "CommandHandlerClient",
    "QueryClient",
    "SpeculativeClient",
    "DomainClient",
    # Router (unified)
    "Router",
    "BuildError",
    "DispatchError",
    "CommandHandlerRouter",
    "SagaRouter",
    "ProcessManagerRouter",
    "ProjectorRouter",
    "UpcasterRouter",
    "SagaHandlerResponse",
    "ProcessManagerResponse",
    "command_handler",
    "saga",
    "process_manager",
    "projector",
    "upcaster",
    "handles",
    "applies",
    "rejected",
    "state_factory",
    "upcasts",
    # gRPC server adapters
    "CommandHandlerGrpc",
    "SagaGrpc",
    "ProcessManagerGrpc",
    "ProjectorGrpc",
    "UpcasterGrpc",
    # Errors
    "ClientError",
    "ConnectionError",
    "TransportError",
    "GRPCError",
    "InvalidArgumentError",
    "InvalidTimestampError",
    "CommandRejectedError",
    # Constants
    "UNKNOWN_DOMAIN",
    "WILDCARD_DOMAIN",
    "DEFAULT_EDITION",
    "META_ANGZARR_DOMAIN",
    "PROJECTION_DOMAIN_PREFIX",
    "PROJECTION_TYPE_URL",
    "TYPE_URL_PREFIX",
    # Helpers
    "destination_map",
    "domain",
    "correlation_id",
    "has_correlation_id",
    "root_uuid",
    "root_id_hex",
    "edition",
    "edition_is_empty",
    "edition_name_or_default",
    "next_sequence",
    "uuid_to_proto",
    "proto_to_uuid",
    "proto_uuid_to_hex",
    "type_url",
    "type_name_from_url",
    "type_url_matches",
    "type_url_matches_exact",
    "full_type_url",
    "full_type_url_for",
    "now",
    "parse_timestamp",
    # Builders
    "CommandBuilder",
    "QueryBuilder",
    # Wrappers
    "CoverW",
    "EventBookW",
    "CommandBookW",
    "QueryW",
    "EventPageW",
    "CommandPageW",
    "CommandResponseW",
    # Server
    "configure_logging",
    "get_transport_config",
    "create_server",
    "run_server",
    "cleanup_socket",
    # Validation
    "require_exists",
    "require_not_exists",
    "require_positive",
    "require_non_negative",
    "require_not_empty",
    "require_not_empty_str",
    "require_status",
    "require_status_not",
    # Identity
    "INVENTORY_PRODUCT_NAMESPACE",
    "compute_root",
    "inventory_product_root",
    "customer_root",
    "product_root",
    "order_root",
    "inventory_root",
    "cart_root",
    "fulfillment_root",
    "to_proto_bytes",
    # Event packing
    "pack_event",
    "pack_events",
    "new_event_book",
    "new_event_book_multi",
    # Compensation
    "CompensationContext",
    "RejectionHandlerResponse",
    "delegate_to_framework",
    "emit_compensation_events",
    "pm_delegate_to_framework",
    "pm_emit_compensation_events",
    # Saga context
    "SagaContext",
    # Destinations
    "Destinations",
]
