# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: angzarr/saga.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'angzarr/saga.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from angzarr_client.proto.angzarr import types_pb2 as angzarr_dot_types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61ngzarr/saga.proto\x12\x07\x61ngzarr\x1a\x13\x61ngzarr/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"?\n\x11SagaHandleRequest\x12*\n\x06source\x18\x01 \x01(\x0b\x32\x12.angzarr.EventBookR\x06source\"L\n\x14SpeculateSagaRequest\x12\x34\n\x07request\x18\x01 \x01(\x0b\x32\x1a.angzarr.SagaHandleRequestR\x07request\"l\n\x0cSagaResponse\x12\x30\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\x14.angzarr.CommandBookR\x08\x63ommands\x12*\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x12.angzarr.EventBookR\x06\x65vents\"\x9d\x03\n\x16SagaCompensationFailed\x12\x41\n\x14triggering_aggregate\x18\x01 \x01(\x0b\x32\x0e.angzarr.CoverR\x13triggeringAggregate\x12:\n\x19triggering_event_sequence\x18\x02 \x01(\rR\x17triggeringEventSequence\x12\x1b\n\tsaga_name\x18\x03 \x01(\tR\x08sagaName\x12)\n\x10rejection_reason\x18\x04 \x01(\tR\x0frejectionReason\x12>\n\x1b\x63ompensation_failure_reason\x18\x05 \x01(\tR\x19\x63ompensationFailureReason\x12?\n\x10rejected_command\x18\x06 \x01(\x0b\x32\x14.angzarr.CommandBookR\x0frejectedCommand\x12;\n\x0boccurred_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\noccurredAt2J\n\x0bSagaService\x12;\n\x06Handle\x12\x1a.angzarr.SagaHandleRequest\x1a\x15.angzarr.SagaResponse2\xe8\x01\n\x16SagaCoordinatorService\x12Y\n\x07\x45xecute\x12\x1a.angzarr.SagaHandleRequest\x1a\x15.angzarr.SagaResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/v1/saga/execute:\x01*\x12s\n\x12\x45xecuteSpeculative\x12\x1d.angzarr.SpeculateSagaRequest\x1a\x15.angzarr.SagaResponse\"\'\x82\xd3\xe4\x93\x02!\"\x1c/v1/saga/execute/speculative:\x01*B~\n\x0b\x63om.angzarrB\tSagaProtoP\x01Z(github.com/angzarr/angzarr/proto/angzarr\xa2\x02\x03\x41XX\xaa\x02\x07\x41ngzarr\xca\x02\x07\x41ngzarr\xe2\x02\x13\x41ngzarr\\GPBMetadata\xea\x02\x07\x41ngzarrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'angzarr.saga_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.angzarrB\tSagaProtoP\001Z(github.com/angzarr/angzarr/proto/angzarr\242\002\003AXX\252\002\007Angzarr\312\002\007Angzarr\342\002\023Angzarr\\GPBMetadata\352\002\007Angzarr'
  _globals['_SAGACOORDINATORSERVICE'].methods_by_name['Execute']._loaded_options = None
  _globals['_SAGACOORDINATORSERVICE'].methods_by_name['Execute']._serialized_options = b'\202\323\344\223\002\025\"\020/v1/saga/execute:\001*'
  _globals['_SAGACOORDINATORSERVICE'].methods_by_name['ExecuteSpeculative']._loaded_options = None
  _globals['_SAGACOORDINATORSERVICE'].methods_by_name['ExecuteSpeculative']._serialized_options = b'\202\323\344\223\002!\"\034/v1/saga/execute/speculative:\001*'
  _globals['_SAGAHANDLEREQUEST']._serialized_start=115
  _globals['_SAGAHANDLEREQUEST']._serialized_end=178
  _globals['_SPECULATESAGAREQUEST']._serialized_start=180
  _globals['_SPECULATESAGAREQUEST']._serialized_end=256
  _globals['_SAGARESPONSE']._serialized_start=258
  _globals['_SAGARESPONSE']._serialized_end=366
  _globals['_SAGACOMPENSATIONFAILED']._serialized_start=369
  _globals['_SAGACOMPENSATIONFAILED']._serialized_end=782
  _globals['_SAGASERVICE']._serialized_start=784
  _globals['_SAGASERVICE']._serialized_end=858
  _globals['_SAGACOORDINATORSERVICE']._serialized_start=861
  _globals['_SAGACOORDINATORSERVICE']._serialized_end=1093
# @@protoc_insertion_point(module_scope)
